language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fanta' ]; then cd .. && eval "mv $currentfolder generator-fanta" && cd generator-fanta; fi

