// Generated by CoffeeScript 1.7.1
'use strict';
var FantaGenerator, chalk, path, util, yeoman, yosay,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

util = require('util');

path = require('path');

yeoman = require('yeoman-generator');

yosay = require('yosay');

chalk = require('chalk');

FantaGenerator = (function(_super) {
  __extends(FantaGenerator, _super);

  function FantaGenerator() {
    yeoman.generators.Base.apply(this, arguments);
    this.manifest = {};
    this.sourceRoot(path.join(__dirname, 'templates'));
    this.pkg = require('../package.json');
    this.on('end', function() {
      if (!this.options['skip-install']) {
        return this.installDependencies();
      }
    });
  }

  FantaGenerator.prototype.askFor = function() {
    var done, prompts;
    done = this.async();
    this.log(yosay('Welcome to the marvelous Fanta generator!'));
    prompts = [
      {
        name: 'appname',
        message: 'Set Your App Name(default: fantaApp)',
        "default": this.appname ? this.appname : 'fantaApp'
      }, {
        name: 'description',
        message: 'How would you like to describe this extension?',
        "default": 'My Fanta App'
      }, {
        type: 'list',
        name: 'apptype',
        message: 'Would you like to create app below?',
        choices: ['web-app', 'chrome-extension', 'node-app']
      }, {
        type: 'checkbox',
        name: 'uifeatures',
        message: 'What more would you like?',
        choices: [
          {
            name: 'bootstrap',
            value: 'includeBootstrap',
            checked: true
          }, {
            value: 'Modernizr',
            name: 'includeModernizr',
            checked: false
          }, {
            value: 'less',
            name: 'includeLess',
            checked: true
          }
        ]
      }
    ];
    return this.prompt(prompts, (function(_this) {
      return function(answers) {
        var isChecked;
        isChecked = function(choices, value) {
          return choices.indexOf(value) > -1;
        };
        _this.appname = _this.manifest.name = answers.appname.replace(/\"/g, '\\"');
        _this.manifest.description = answers.description.replace(/\"/g, '\\"');
        _this.manifest.apptype = answers.apptype;
        console.log(_this.manifest.apptype);
        return done();
      };
    })(this));
  };

  return FantaGenerator;

})(yeoman.generators.Base);

FantaGenerator.prototype.projectfiles = function() {
  this.copy('editorconfig', '.editorconfig');
  return this.copy('jshintrc', '.jshintrc');
};

FantaGenerator.prototype.gruntfile = function() {
  return this.template('Gruntfile.js');
};

FantaGenerator.prototype.packageJSON = function() {
  return this.template('_package.json', 'package.json');
};

FantaGenerator.prototype.bowerJSON = function() {
  return this.template('_bower.json', 'bower.json');
};

FantaGenerator.prototype.app = function() {
  this.mkdir('app');
  this.mkdir('app/scripts');
  this.mkdir('app/styles');
  this.mkdir('app/views');
  return this.mkdir('app/templates');
};

module.exports = FantaGenerator;
